python ./glcm_cnn.py asm
python ./glcm_cnn.py contrast
python ./glcm_cnn.py dissimilarity
python ./glcm_cnn.py energy
python ./glcm_cnn.py entropy
python ./glcm_cnn.py homogeneity
python ./glcm_cnn.py max
python ./glcm_cnn.py mean 
python ./glcm_cnn.py standard
python ./glcm_cnn.py rgb_image